name: Release

on:
  push:
    tags:
      - '*'

jobs:

  release:
    strategy:
      matrix:
        go: [1.14]

    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}-stretch

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: make
      - name: release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
